# Generated by Django 3.2.3 on 2021-07-29 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210708_2204'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
